- name: Update Global Configuration
  ldap_attr_custom:
    params: "{{ ldap_params }}"
    dn: "inum={{ gluu_inum_appliance }},ou=appliances,o=gluu"
    name: "{{ item.key }}"
    state: exact
    values: "{{ item.value }}"
  with_dict:
    "{{ gluu_appliances | default({}) }}"

- name: Update Global Configuration - Get current configuration
  ldap_get:
    params: "{{ ldap_params }}"
    dn: "inum={{ gluu_inum_appliance }},ou=appliances,o=gluu"
  register: gluu_appliances_ldap_entry

- name: Update Global Configuration - Update configuration
  ldap_attr_custom:
    params: "{{ ldap_params }}"
    dn: "inum={{ gluu_inum_appliance }},ou=appliances,o=gluu"
    name: "{{ item.key }}"
    values: "{{ gluu_appliances_ldap_entry.results[1][item.key][0] | jsonpatch(operations=item.value, to_json=True) }}"
    state: exact
  with_dict:
    "{{ gluu_appliances_json_operations | default({}) }}"
