- name: Update OpenID Connect - Scopes - Set default attributes
  set_fact:
    gluu_openid_connect_scopes_default:
      objectClass:
        - top
        - oxAuthCustomScope

- name: Update OpenID Connect - Scopes - User With Inum
  ldap_upsert:
    params: "{{ ldap_params }}"
    dn: "{{ item.inum | gluu_concat_inum(base_inum=gluu_inum_org, inum_type='0009', dn='scopes') }}"
    attributes:
      "{{ gluu_openid_connect_scopes_default | combine(item, recursive=True) | gluu_concat_inum(base_inum=gluu_inum_org, inum_type='0009') | gluu_concat_inum(key='oxAuthClaim', base_inum=gluu_inum_org, inum_type='0005', dn='attributes') }}"
  with_items:
    "{{ gluu_openid_connect_scopes | default([]) }}"
  when: item.inum is defined
  loop_control:
    label: "{{ item.displayName }}"

- name: Update OpenID Connect - Scopes - User Without Inum
  ldap_upsert:
    params: "{{ ldap_params }}"
    search_filter: "(&(objectClass=oxAuthCustomScope)(displayName={{ item.displayName }}))"
    attributes:
      "{{ gluu_openid_connect_scopes_default | combine(item, recursive=True) | gluu_concat_inum(key='oxAuthClaim', base_inum=gluu_inum_org, inum_type='0005', dn='attributes') }}"
  with_items:
    "{{ gluu_openid_connect_scopes | default([]) }}"
  when: item.inum is not defined
  loop_control:
    label: "{{ item.displayName }}"
