

- name: Update oxAuth Configuration - Get current configuration
  ldap_get:
    params: "{{ ldap_params }}"
    dn: ou=oxauth,ou=configuration,inum={{ gluu_inum_appliance }},ou=appliances,o=gluu
  register: gluu_oxauth_ldap_entry
  

- name: Update oxAuth Configuration - Update configuration
  ldap_attr_custom:
    params: "{{ ldap_params }}"
    dn: ou=oxauth,ou=configuration,inum={{ gluu_inum_appliance }},ou=appliances,o=gluu
    name: "{{ item.key }}"
    values: "{{ gluu_oxauth_ldap_entry.results[1][item.key][0] | jsonpatch(operations=item.value) | to_json }}"
    state: exact
  with_dict:
    "{{ gluu_oxauth_json_operations | default({}) }}"
