

- name: Update oxTrust Configuration - Get current configuration
  ldap_get:
    params: "{{ ldap_params }}"
    dn: ou=oxtrust,ou=configuration,inum={{ gluu_inum_appliance }},ou=appliances,o=gluu
  register: gluu_oxtrust_ldap_entry
  

- name: Update oxTrust Configuration - Update configuration
  ldap_attr_custom:
    params: "{{ ldap_params }}"
    dn: ou=oxtrust,ou=configuration,inum={{ gluu_inum_appliance }},ou=appliances,o=gluu
    name: "{{ item.key }}"
    values: "{{ gluu_oxtrust_ldap_entry.results[1][item.key][0] | jsonpatch(operations=item.value) | to_json }}"
    state: exact
  with_dict:
    "{{ gluu_oxtrust_json_operations | default({}) }}"
