- set_fact:
    idp_auth_ldap_server_list: ""

- name: "Gluu Cluster Configuration - Generate LDAP server list"
  set_fact:
    idp_auth_ldap_server_list: "{{ idp_auth_ldap_server_list }},{{ hostvars[item]['gluu_internal_hostname'] }}:1636"
  when:  "'ldap' in hostvars[item]['gluu_modules']"
  with_items:
    "{{ groups['gluu-servers'] }}"

- name: "Gluu Cluster Configuration - Set all LDAP servers for authentication auth_ldap_server"
  ldap_attr_custom:
    params: "{{ ldap_params }}"
    dn: "inum={{ gluu_inum_appliance }},ou=appliances,o=gluu"
    name: "{{ item.key }}"
    values: "{{ gluu_appliances_ldap_entry.results[1][item.key][0] | jsonpatch(operations=item.value, to_json=True) }}"
    state: exact
  with_dict:
    oxIDPAuthentication:
      - insertOrReplace:
          path: '/config'
          # Add a space to keep the value as a string and to avoind ansible to convert it into a dictionary
          value: " {\"configId\":\"auth_ldap_server\",\"bindDN\":\"cn=directory manager,o=gluu\",\"bindPassword\":\"{{ gluu_ldap_admin_password | gluu_encrypt_password(secret=gluu_ldap_salt_password) }}\",\"servers\":[\"{{ gluu_ldap_hostname | default(idp_auth_ldap_server_list) | regex_replace('^,', '') | regex_replace(',', '\",\"') }}\"],\"maxConnections\":1000,\"useSSL\":true,\"baseDNs\":[\"o=gluu\"],\"primaryKey\":\"uid\",\"localPrimaryKey\":\"uid\",\"useAnonymousBind\":false,\"enabled\":true,\"version\":0,\"level\":0}"
